#ifndef NAR_SDL_H
#define NAR_SDL_H

//Blend
#define Nar_SDL_Blend_BlendMode "Nar.SDL.Blend.BlendMode"
#define Nar_SDL_Blend_BlendMode__BlendModeNone "Nar.SDL.Blend.Mode#BlendModeNone"
#define Nar_SDL_Blend_BlendMode__BlendModeBlend "Nar.SDL.Blend.Mode#BlendModeBlend"
#define Nar_SDL_Blend_BlendMode__BlendModeAdd "Nar.SDL.Blend.Mode#BlendModeAdd"
#define Nar_SDL_Blend_BlendMode__BlendModeMod "Nar.SDL.Blend.Mode#BlendModeMod"
#define Nar_SDL_Blend_BlendMode__BlendModeMul "Nar.SDL.Blend.Mode#BlendModeMul"
#define Nar_SDL_Blend_BlendMode__BlendModeInvalid "Nar.SDL.Blend.Mode#BlendModeInvalid"
#define Nar_SDL_Blend_BlendMode__BlendModeCustom "Nar.SDL.Blend.Mode#BlendModeCustom"

#define Nar_SDL_Blend_BlendOperation "Nar.SDL.Blend.BlendOperation"
#define Nar_SDL_Blend_BlendOperation__BlendOperationAdd "Nar.SDL.Blend.BlendOperation#BlendOperationAdd"
#define Nar_SDL_Blend_BlendOperation__BlendOperationSubtract "Nar.SDL.Blend.BlendOperation#BlendOperationSubtract"
#define Nar_SDL_Blend_BlendOperation__BlendOperationRevSubtract "Nar.SDL.Blend.BlendOperation#BlendOperationRevSubtract"
#define Nar_SDL_Blend_BlendOperation__BlendOperationMinimum "Nar.SDL.Blend.BlendOperation#BlendOperationMinimum"
#define Nar_SDL_Blend_BlendOperation__BlendOperationMaximum "Nar.SDL.Blend.BlendOperation#BlendOperationMaximum"

#define Nar_SDL_Blend_BlendFactor "Nar.SDL.Blend.BlendFactor"
#define Nar_SDL_Blend_BlendFactor__BlendFactorZero "Nar.SDL.Blend.BlendFactor#BlendFactorZero"
#define Nar_SDL_Blend_BlendFactor__BlendFactorOne "Nar.SDL.Blend.BlendFactor#BlendFactorOne"
#define Nar_SDL_Blend_BlendFactor__BlendFactorSrcColor "Nar.SDL.Blend.BlendFactor#BlendFactorSrcColor"
#define Nar_SDL_Blend_BlendFactor__BlendFactorOneMinusSrcColor "Nar.SDL.Blend.BlendFactor#BlendFactorOneMinusSrcColor"
#define Nar_SDL_Blend_BlendFactor__BlendFactorSrcAlpha "Nar.SDL.Blend.BlendFactor#BlendFactorSrcAlpha"
#define Nar_SDL_Blend_BlendFactor__BlendFactorOneMinusSrcAlpha "Nar.SDL.Blend.BlendFactor#BlendFactorOneMinusSrcAlpha"
#define Nar_SDL_Blend_BlendFactor__BlendFactorDstColor "Nar.SDL.Blend.BlendFactor#BlendFactorDstColor"
#define Nar_SDL_Blend_BlendFactor__BlendFactorOneMinusDstColor "Nar.SDL.Blend.BlendFactor#BlendFactorOneMinusDstColor"
#define Nar_SDL_Blend_BlendFactor__BlendFactorDstAlpha "Nar.SDL.Blend.BlendFactor#BlendFactorDstAlpha"
#define Nar_SDL_Blend_BlendFactor__BlendFactorOneMinusDstAlpha "Nar.SDL.Blend.BlendFactor#BlendFactorOneMinusDstAlpha"

//MessageBox
#define Nar_SDL_MessageBox_MessageBoxIcon "Nar.SDL.MessageBox.MessageBoxIcon"
#define Nar_SDL_MessageBox_MessageBoxIcon__MessageBoxIconError "Nar.SDL.MessageBox.MessageBoxIcon#MessageBoxIconError"
#define Nar_SDL_MessageBox_MessageBoxIcon__MessageBoxIconWarning "Nar.SDL.MessageBox.MessageBoxIcon#MessageBoxIconWarning"
#define Nar_SDL_MessageBox_MessageBoxIcon__MessageBoxIconInformation "Nar.SDL.MessageBox.MessageBoxIcon#MessageBoxIconInformation"

#define Nar_SDL_MessageBox_MessageBoxButtonsLayout "Nar.SDL.MessageBox.MessageBoxButtonsLayout"
#define Nar_SDL_MessageBox_MessageBoxButtonsLayout__MessageBoxButtonsLayoutLeftToRight "Nar.SDL.MessageBox.MessageBoxButtonsLayout#MessageBoxButtonsLayoutLeftToRight"
#define Nar_SDL_MessageBox_MessageBoxButtonsLayout__MessageBoxButtonsLayoutRightToLeft "Nar.SDL.MessageBox.MessageBoxButtonsLayout#MessageBoxButtonsLayoutRightToLeft"

#define Nar_SDL_MessageBox_MessageBoxButtonFlag "Nar.SDL.MessageBox.MessageBoxButtonFlag"
#define Nar_SDL_MessageBox_MessageBoxButtonFlag__MessageBoxButtonFlagNone "Nar.SDL.MessageBox.MessageBoxButtonFlag#MessageBoxButtonFlagNone"
#define Nar_SDL_MessageBox_MessageBoxButtonFlag__MessageBoxButtonFlagReturnKeyDefault "Nar.SDL.MessageBox.MessageBoxButtonFlag#MessageBoxButtonFlagReturnKeyDefault"
#define Nar_SDL_MessageBox_MessageBoxButtonFlag__MessageBoxButtonFlagEscapeKeyDefault "Nar.SDL.MessageBox.MessageBoxButtonFlag#MessageBoxButtonFlagEscapeKeyDefault"

//Pixel
#define Nar_SDL_Pixels_PixelType "Nar.SDL.Pixels.PixelType"
#define Nar_SDL_Pixels_PixelType__PixelTypeUnknown "Nar.SDL.Pixels.PixelType#PixelTypeUnknown"
#define Nar_SDL_Pixels_PixelType__PixelTypeIndex1 "Nar.SDL.Pixels.PixelType#PixelTypeIndex1"
#define Nar_SDL_Pixels_PixelType__PixelTypeIndex4 "Nar.SDL.Pixels.PixelType#PixelTypeIndex4"
#define Nar_SDL_Pixels_PixelType__PixelTypeIndex8 "Nar.SDL.Pixels.PixelType#PixelTypeIndex8"
#define Nar_SDL_Pixels_PixelType__PixelTypePacked8 "Nar.SDL.Pixels.PixelType#PixelTypePacked8"
#define Nar_SDL_Pixels_PixelType__PixelTypePacked16 "Nar.SDL.Pixels.PixelType#PixelTypePacked16"
#define Nar_SDL_Pixels_PixelType__PixelTypePacked32 "Nar.SDL.Pixels.PixelType#PixelTypePacked32"
#define Nar_SDL_Pixels_PixelType__PixelTypeArrayU8 "Nar.SDL.Pixels.PixelType#PixelTypeArrayU8"
#define Nar_SDL_Pixels_PixelType__PixelTypeArrayU16 "Nar.SDL.Pixels.PixelType#PixelTypeArrayU16"
#define Nar_SDL_Pixels_PixelType__PixelTypeArrayU32 "Nar.SDL.Pixels.PixelType#PixelTypeArrayU32"
#define Nar_SDL_Pixels_PixelType__PixelTypeArrayF16 "Nar.SDL.Pixels.PixelType#PixelTypeArrayF16"
#define Nar_SDL_Pixels_PixelType__PixelTypeArrayF32 "Nar.SDL.Pixels.PixelType#PixelTypeArrayF32"

#define Nar_SDL_Pixels_BitmapOrder "Nar.SDL.Pixels.BitmapOrder"
#define Nar_SDL_Pixels_BitmapOrder__BitmapOrderNone "Nar.SDL.Pixels.BitmapOrder#BitmapOrderNone"
#define Nar_SDL_Pixels_BitmapOrder__BitmapOrder4321 "Nar.SDL.Pixels.BitmapOrder#BitmapOrder4321"
#define Nar_SDL_Pixels_BitmapOrder__BitmapOrder1234 "Nar.SDL.Pixels.BitmapOrder#BitmapOrder1234"

#define Nar_SDL_Pixels_PackedOrder "Nar.SDL.Pixels.PackedOrder"
#define Nar_SDL_Pixels_PackedOrder__PackedOrderNone "Nar.SDL.Pixels.PackedOrder#PackedOrderNone"
#define Nar_SDL_Pixels_PackedOrder__PackedOrderXRGB "Nar.SDL.Pixels.PackedOrder#PackedOrderXRGB"
#define Nar_SDL_Pixels_PackedOrder__PackedOrderRGBX "Nar.SDL.Pixels.PackedOrder#PackedOrderRGBX"
#define Nar_SDL_Pixels_PackedOrder__PackedOrderARGB "Nar.SDL.Pixels.PackedOrder#PackedOrderARGB"
#define Nar_SDL_Pixels_PackedOrder__PackedOrderRGBA "Nar.SDL.Pixels.PackedOrder#PackedOrderRGBA"
#define Nar_SDL_Pixels_PackedOrder__PackedOrderXBGR "Nar.SDL.Pixels.PackedOrder#PackedOrderXBGR"
#define Nar_SDL_Pixels_PackedOrder__PackedOrderBGRX "Nar.SDL.Pixels.PackedOrder#PackedOrderBGRX"
#define Nar_SDL_Pixels_PackedOrder__PackedOrderABGR "Nar.SDL.Pixels.PackedOrder#PackedOrderABGR"
#define Nar_SDL_Pixels_PackedOrder__PackedOrderBGRA "Nar.SDL.Pixels.PackedOrder#PackedOrderBGRA"

#define Nar_SDL_Pixels_ArrayOrder "Nar.SDL.Pixels.ArrayOrder"
#define Nar_SDL_Pixels_ArrayOrder__ArrayOrderNone "Nar.SDL.Pixels.ArrayOrder#ArrayOrderNone"
#define Nar_SDL_Pixels_ArrayOrder__ArrayOrderRGB "Nar.SDL.Pixels.ArrayOrder#ArrayOrderRGB"
#define Nar_SDL_Pixels_ArrayOrder__ArrayOrderRGBA "Nar.SDL.Pixels.ArrayOrder#ArrayOrderRGBA"
#define Nar_SDL_Pixels_ArrayOrder__ArrayOrderARGB "Nar.SDL.Pixels.ArrayOrder#ArrayOrderARGB"
#define Nar_SDL_Pixels_ArrayOrder__ArrayOrderBGR "Nar.SDL.Pixels.ArrayOrder#ArrayOrderBGR"
#define Nar_SDL_Pixels_ArrayOrder__ArrayOrderBGRA "Nar.SDL.Pixels.ArrayOrder#ArrayOrderBGRA"
#define Nar_SDL_Pixels_ArrayOrder__ArrayOrderABGR "Nar.SDL.Pixels.ArrayOrder#ArrayOrderABGR"

#define Nar_SDL_Pixels_PackedLayout "Nar.SDL.Pixels.PackedLayout"
#define Nar_SDL_Pixels_PackedLayout__PackedLayoutNone "Nar.SDL.Pixels.PackedLayout#PackedLayoutNone"
#define Nar_SDL_Pixels_PackedLayout__PackedLayout332 "Nar.SDL.Pixels.PackedLayout#PackedLayout332"
#define Nar_SDL_Pixels_PackedLayout__PackedLayout4444 "Nar.SDL.Pixels.PackedLayout#PackedLayout4444"
#define Nar_SDL_Pixels_PackedLayout__PackedLayout1555 "Nar.SDL.Pixels.PackedLayout#PackedLayout1555"
#define Nar_SDL_Pixels_PackedLayout__PackedLayout5551 "Nar.SDL.Pixels.PackedLayout#PackedLayout5551"
#define Nar_SDL_Pixels_PackedLayout__PackedLayout565 "Nar.SDL.Pixels.PackedLayout#PackedLayout565"
#define Nar_SDL_Pixels_PackedLayout__PackedLayout8888 "Nar.SDL.Pixels.PackedLayout#PackedLayout8888"
#define Nar_SDL_Pixels_PackedLayout__PackedLayout2101010 "Nar.SDL.Pixels.PackedLayout#PackedLayout2101010"
#define Nar_SDL_Pixels_PackedLayout__PackedLayout1010102 "Nar.SDL.Pixels.PackedLayout#PackedLayout1010102"

#define Nar_SDL_Pixels_PixelFormat "Nar.SDL.Pixels.PixelFormat"
#define Nar_SDL_Pixels_PixelFormat__PixelFormatIndex1LSB "Nar.SDL.Pixels.PixelFormat#PixelFormatIndex1LSB"
#define Nar_SDL_Pixels_PixelFormat__PixelFormatIndex1MSB "Nar.SDL.Pixels.PixelFormat#PixelFormatIndex1MSB"
#define Nar_SDL_Pixels_PixelFormat__PixelFormatIndex2LSB "Nar.SDL.Pixels.PixelFormat#PixelFormatIndex2LSB"
#define Nar_SDL_Pixels_PixelFormat__PixelFormatIndex2MSB "Nar.SDL.Pixels.PixelFormat#PixelFormatIndex2MSB"
#define Nar_SDL_Pixels_PixelFormat__PixelFormatIndex4LSB "Nar.SDL.Pixels.PixelFormat#PixelFormatIndex4LSB"
#define Nar_SDL_Pixels_PixelFormat__PixelFormatIndex4MSB "Nar.SDL.Pixels.PixelFormat#PixelFormatIndex4MSB"
#define Nar_SDL_Pixels_PixelFormat__PixelFormatIndex8 "Nar.SDL.Pixels.PixelFormat#PixelFormatIndex8"
#define Nar_SDL_Pixels_PixelFormat__PixelFormatRGB332 "Nar.SDL.Pixels.PixelFormat#PixelFormatRGB332"
#define Nar_SDL_Pixels_PixelFormat__PixelFormatXRGB4444 "Nar.SDL.Pixels.PixelFormat#PixelFormatXRGB4444"
#define Nar_SDL_Pixels_PixelFormat__PixelFormatRGB444 "Nar.SDL.Pixels.PixelFormat#PixelFormatRGB444"
#define Nar_SDL_Pixels_PixelFormat__PixelFormatXBGR4444 "Nar.SDL.Pixels.PixelFormat#PixelFormatXBGR4444"
#define Nar_SDL_Pixels_PixelFormat__PixelFormatBGR444 "Nar.SDL.Pixels.PixelFormat#PixelFormatBGR444"
#define Nar_SDL_Pixels_PixelFormat__PixelFormatXRGB1555 "Nar.SDL.Pixels.PixelFormat#PixelFormatXRGB1555"
#define Nar_SDL_Pixels_PixelFormat__PixelFormatRGB555 "Nar.SDL.Pixels.PixelFormat#PixelFormatRGB555"
#define Nar_SDL_Pixels_PixelFormat__PixelFormatXBGR1555 "Nar.SDL.Pixels.PixelFormat#PixelFormatXBGR1555"
#define Nar_SDL_Pixels_PixelFormat__PixelFormatBGR555 "Nar.SDL.Pixels.PixelFormat#PixelFormatBGR555"
#define Nar_SDL_Pixels_PixelFormat__PixelFormatARGB4444 "Nar.SDL.Pixels.PixelFormat#PixelFormatARGB4444"
#define Nar_SDL_Pixels_PixelFormat__PixelFormatRGBA4444 "Nar.SDL.Pixels.PixelFormat#PixelFormatRGBA4444"
#define Nar_SDL_Pixels_PixelFormat__PixelFormatABGR4444 "Nar.SDL.Pixels.PixelFormat#PixelFormatABGR4444"
#define Nar_SDL_Pixels_PixelFormat__PixelFormatBGRA4444 "Nar.SDL.Pixels.PixelFormat#PixelFormatBGRA4444"
#define Nar_SDL_Pixels_PixelFormat__PixelFormatARGB1555 "Nar.SDL.Pixels.PixelFormat#PixelFormatARGB1555"
#define Nar_SDL_Pixels_PixelFormat__PixelFormatRGBA5551 "Nar.SDL.Pixels.PixelFormat#PixelFormatRGBA5551"
#define Nar_SDL_Pixels_PixelFormat__PixelFormatABGR1555 "Nar.SDL.Pixels.PixelFormat#PixelFormatABGR1555"
#define Nar_SDL_Pixels_PixelFormat__PixelFormatBGRA5551 "Nar.SDL.Pixels.PixelFormat#PixelFormatBGRA5551"
#define Nar_SDL_Pixels_PixelFormat__PixelFormatRGB565 "Nar.SDL.Pixels.PixelFormat#PixelFormatRGB565"
#define Nar_SDL_Pixels_PixelFormat__PixelFormatBGR565 "Nar.SDL.Pixels.PixelFormat#PixelFormatBGR565"
#define Nar_SDL_Pixels_PixelFormat__PixelFormatRGB24 "Nar.SDL.Pixels.PixelFormat#PixelFormatRGB24"
#define Nar_SDL_Pixels_PixelFormat__PixelFormatBGR24 "Nar.SDL.Pixels.PixelFormat#PixelFormatBGR24"
#define Nar_SDL_Pixels_PixelFormat__PixelFormatXRGB8888 "Nar.SDL.Pixels.PixelFormat#PixelFormatXRGB8888"
#define Nar_SDL_Pixels_PixelFormat__PixelFormatRGB888 "Nar.SDL.Pixels.PixelFormat#PixelFormatRGB888"
#define Nar_SDL_Pixels_PixelFormat__PixelFormatRGBX8888 "Nar.SDL.Pixels.PixelFormat#PixelFormatRGBX8888"
#define Nar_SDL_Pixels_PixelFormat__PixelFormatXBGR8888 "Nar.SDL.Pixels.PixelFormat#PixelFormatXBGR8888"
#define Nar_SDL_Pixels_PixelFormat__PixelFormatBGR888 "Nar.SDL.Pixels.PixelFormat#PixelFormatBGR888"
#define Nar_SDL_Pixels_PixelFormat__PixelFormatBGRX8888 "Nar.SDL.Pixels.PixelFormat#PixelFormatBGRX8888"
#define Nar_SDL_Pixels_PixelFormat__PixelFormatARGB8888 "Nar.SDL.Pixels.PixelFormat#PixelFormatARGB8888"
#define Nar_SDL_Pixels_PixelFormat__PixelFormatRGBA8888 "Nar.SDL.Pixels.PixelFormat#PixelFormatRGBA8888"
#define Nar_SDL_Pixels_PixelFormat__PixelFormatABGR8888 "Nar.SDL.Pixels.PixelFormat#PixelFormatABGR8888"
#define Nar_SDL_Pixels_PixelFormat__PixelFormatBGRA8888 "Nar.SDL.Pixels.PixelFormat#PixelFormatBGRA8888"
#define Nar_SDL_Pixels_PixelFormat__PixelFormatARGB2101010 "Nar.SDL.Pixels.PixelFormat#PixelFormatARGB2101010"
#define Nar_SDL_Pixels_PixelFormat__PixelFormatRGBA32 "Nar.SDL.Pixels.PixelFormat#PixelFormatRGBA32"
#define Nar_SDL_Pixels_PixelFormat__PixelFormatARGB32 "Nar.SDL.Pixels.PixelFormat#PixelFormatARGB32"
#define Nar_SDL_Pixels_PixelFormat__PixelFormatBGRA32 "Nar.SDL.Pixels.PixelFormat#PixelFormatBGRA32"
#define Nar_SDL_Pixels_PixelFormat__PixelFormatABGR32 "Nar.SDL.Pixels.PixelFormat#PixelFormatABGR32"
#define Nar_SDL_Pixels_PixelFormat__PixelFormatRGBX32 "Nar.SDL.Pixels.PixelFormat#PixelFormatRGBX32"
#define Nar_SDL_Pixels_PixelFormat__PixelFormatXRGB32 "Nar.SDL.Pixels.PixelFormat#PixelFormatXRGB32"
#define Nar_SDL_Pixels_PixelFormat__PixelFormatBGRX32 "Nar.SDL.Pixels.PixelFormat#PixelFormatBGRX32"
#define Nar_SDL_Pixels_PixelFormat__PixelFormatXBGR32 "Nar.SDL.Pixels.PixelFormat#PixelFormatXBGR32"
#define Nar_SDL_Pixels_PixelFormat__PixelFormatYV12 "Nar.SDL.Pixels.PixelFormat#PixelFormatYV12"
#define Nar_SDL_Pixels_PixelFormat__PixelFormatIYUV "Nar.SDL.Pixels.PixelFormat#PixelFormatIYUV"
#define Nar_SDL_Pixels_PixelFormat__PixelFormatYUY2 "Nar.SDL.Pixels.PixelFormat#PixelFormatYUY2"
#define Nar_SDL_Pixels_PixelFormat__PixelFormatUYVY "Nar.SDL.Pixels.PixelFormat#PixelFormatUYVY"
#define Nar_SDL_Pixels_PixelFormat__PixelFormatYVYU "Nar.SDL.Pixels.PixelFormat#PixelFormatYVYU"
#define Nar_SDL_Pixels_PixelFormat__PixelFormatNV12 "Nar.SDL.Pixels.PixelFormat#PixelFormatNV12"
#define Nar_SDL_Pixels_PixelFormat__PixelFormatNV21 "Nar.SDL.Pixels.PixelFormat#PixelFormatNV21"
#define Nar_SDL_Pixels_PixelFormat__PixelFormatExternalOES "Nar.SDL.Pixels.PixelFormat#PixelFormatExternalOES"

//Renderer
#define Nar_SDL_Render_RendererFlag "Nar.SDL.Render.RendererFlag"
#define Nar_SDL_Render_RendererFlag__RendererFlagSoftware "Nar.SDL.Render.RendererFlag#RendererFlagSoftware"
#define Nar_SDL_Render_RendererFlag__RendererFlagAccelerated "Nar.SDL.Render.RendererFlag#RendererFlagAccelerated"
#define Nar_SDL_Render_RendererFlag__RendererFlagPresentVSync "Nar.SDL.Render.RendererFlag#RendererFlagPresentVSync"
#define Nar_SDL_Render_RendererFlag__RendererFlagTargetTexture "Nar.SDL.Render.RendererFlag#RendererFlagTargetTexture"

#define Nar_SDL_Render_ScaleMode "Nar.SDL.Render.ScaleMode"
#define Nar_SDL_Render_ScaleMode__ScaleModeNearest "Nar.SDL.Render.ScaleMode#ScaleModeNearest"
#define Nar_SDL_Render_ScaleMode__ScaleModeLinear "Nar.SDL.Render.ScaleMode#ScaleModeLinear"
#define Nar_SDL_Render_ScaleMode__ScaleModeBest "Nar.SDL.Render.ScaleMode#ScaleModeBest"

#define Nar_SDL_Render_TextureAccess "Nar.SDL.Render.TextureAccess"
#define Nar_SDL_Render_TextureAccess__TextureAccessStatic "Nar.SDL.Render.TextureAccess#TextureAccessStatic"
#define Nar_SDL_Render_TextureAccess__TextureAccessStreaming "Nar.SDL.Render.TextureAccess#TextureAccessStreaming"
#define Nar_SDL_Render_TextureAccess__TextureAccessTarget "Nar.SDL.Render.TextureAccess#TextureAccessTarget"

#define Nar_SDL_Render_TextureModulate "Nar.SDL.Render.TextureModulate"
#define Nar_SDL_Render_TextureModulate__TextureModulateNone "Nar.SDL.Render.TextureModulate#TextureModulateNone"
#define Nar_SDL_Render_TextureModulate__TextureModulateColor "Nar.SDL.Render.TextureModulate#TextureModulateColor"
#define Nar_SDL_Render_TextureModulate__TextureModulateAlpha "Nar.SDL.Render.TextureModulate#TextureModulateAlpha"

#define Nar_SDL_Render_RendererFlip "Nar.SDL.Render.RendererFlip"
#define Nar_SDL_Render_RendererFlip__RendererFlipNone "Nar.SDL.Render.RendererFlip#RendererFlipNone"
#define Nar_SDL_Render_RendererFlip__RendererFlipHorizontal "Nar.SDL.Render.RendererFlip#RendererFlipHorizontal"
#define Nar_SDL_Render_RendererFlip__RendererFlipVertical "Nar.SDL.Render.RendererFlip#RendererFlipVertical"

//SDL
#define Nar_SDL_InitSubSystem "Nar.SDL.InitSubSystem"
#define Nar_SDL_InitSubSystem__InitTimer "Nar.SDL.InitSubSystem#InitTimer"
#define Nar_SDL_InitSubSystem__InitAudio "Nar.SDL.InitSubSystem#InitAudio"
#define Nar_SDL_InitSubSystem__InitVideo "Nar.SDL.InitSubSystem#InitVideo"
#define Nar_SDL_InitSubSystem__InitJoystick "Nar.SDL.InitSubSystem#InitJoystick"
#define Nar_SDL_InitSubSystem__InitHaptic "Nar.SDL.InitSubSystem#InitHaptic"
#define Nar_SDL_InitSubSystem__InitGameController "Nar.SDL.InitSubSystem#InitGameController"
#define Nar_SDL_InitSubSystem__InitEvents "Nar.SDL.InitSubSystem#InitEvents"
#define Nar_SDL_InitSubSystem__InitSensor "Nar.SDL.InitSubSystem#InitSensor"

//Video
#define Nar_SDL_Video_WindowPosition "Nar.SDL.Video.WindowPosition"
#define Nar_SDL_Video_WindowPosition__WindowPositionUndefined "Nar.SDL.Video.WindowPosition#WindowPositionUndefined"
#define Nar_SDL_Video_WindowPosition__WindowPositionCentered "Nar.SDL.Video.WindowPosition#WindowPositionCentered"
#define Nar_SDL_Video_WindowPosition__WindowPositionAt "Nar.SDL.Video.WindowPosition#WindowPositionAt"

#define Nar_SDL_Video_WindowFlag "Nar.SDL.Video.WindowFlag"
#define Nar_SDL_Video_WindowFlag__WindowFlagFullscreen "Nar.SDL.Video.WindowFlag#WindowFlagFullscreen"
#define Nar_SDL_Video_WindowFlag__WindowFlagOpengl "Nar.SDL.Video.WindowFlag#WindowFlagOpengl"
#define Nar_SDL_Video_WindowFlag__WindowFlagShown "Nar.SDL.Video.WindowFlag#WindowFlagShown"
#define Nar_SDL_Video_WindowFlag__WindowFlagHidden "Nar.SDL.Video.WindowFlag#WindowFlagHidden"
#define Nar_SDL_Video_WindowFlag__WindowFlagBorderless "Nar.SDL.Video.WindowFlag#WindowFlagBorderless"
#define Nar_SDL_Video_WindowFlag__WindowFlagResizable "Nar.SDL.Video.WindowFlag#WindowFlagResizable"
#define Nar_SDL_Video_WindowFlag__WindowFlagMinimized "Nar.SDL.Video.WindowFlag#WindowFlagMinimized"
#define Nar_SDL_Video_WindowFlag__WindowFlagMaximized "Nar.SDL.Video.WindowFlag#WindowFlagMaximized"
#define Nar_SDL_Video_WindowFlag__WindowFlagMouseGrabbed "Nar.SDL.Video.WindowFlag#WindowFlagMouseGrabbed"
#define Nar_SDL_Video_WindowFlag__WindowFlagInputFocus "Nar.SDL.Video.WindowFlag#WindowFlagInputFocus"
#define Nar_SDL_Video_WindowFlag__WindowFlagMouseFocus "Nar.SDL.Video.WindowFlag#WindowFlagMouseFocus"
#define Nar_SDL_Video_WindowFlag__WindowFlagFullscreenDesktop "Nar.SDL.Video.WindowFlag#WindowFlagFullscreenDesktop"
#define Nar_SDL_Video_WindowFlag__WindowFlagForeign "Nar.SDL.Video.WindowFlag#WindowFlagForeign"
#define Nar_SDL_Video_WindowFlag__WindowFlagAllowHighdpi "Nar.SDL.Video.WindowFlag#WindowFlagAllowHighdpi"
#define Nar_SDL_Video_WindowFlag__WindowFlagMouseCapture "Nar.SDL.Video.WindowFlag#WindowFlagMouseCapture"
#define Nar_SDL_Video_WindowFlag__WindowFlagAlwaysOnTop "Nar.SDL.Video.WindowFlag#WindowFlagAlwaysOnTop"
#define Nar_SDL_Video_WindowFlag__WindowFlagSkipTaskbar "Nar.SDL.Video.WindowFlag#WindowFlagSkipTaskbar"
#define Nar_SDL_Video_WindowFlag__WindowFlagUtility "Nar.SDL.Video.WindowFlag#WindowFlagUtility"
#define Nar_SDL_Video_WindowFlag__WindowFlagTooltip "Nar.SDL.Video.WindowFlag#WindowFlagTooltip"
#define Nar_SDL_Video_WindowFlag__WindowFlagPopupMenu "Nar.SDL.Video.WindowFlag#WindowFlagPopupMenu"
#define Nar_SDL_Video_WindowFlag__WindowFlagKeyboardGrabbed "Nar.SDL.Video.WindowFlag#WindowFlagKeyboardGrabbed"
#define Nar_SDL_Video_WindowFlag__WindowFlagVulkan "Nar.SDL.Video.WindowFlag#WindowFlagVulkan"
#define Nar_SDL_Video_WindowFlag__WindowFlagMetal "Nar.SDL.Video.WindowFlag#WindowFlagMetal"
#define Nar_SDL_Video_WindowFlag__WindowFlagInputGrabbed "Nar.SDL.Video.WindowFlag#WindowFlagInputGrabbed"

#define Nar_SDL_Video_WindowEvent "Nar.SDL.Video.WindowEvent"
#define Nar_SDL_Video_WindowEvent__WindowEventNone "Nar.SDL.Video.WindowEvent#WindowEventNone"
#define Nar_SDL_Video_WindowEvent__WindowEventShown "Nar.SDL.Video.WindowEvent#WindowEventShown"
#define Nar_SDL_Video_WindowEvent__WindowEventHidden "Nar.SDL.Video.WindowEvent#WindowEventHidden"
#define Nar_SDL_Video_WindowEvent__WindowEventExposed "Nar.SDL.Video.WindowEvent#WindowEventExposed"
#define Nar_SDL_Video_WindowEvent__WindowEventMoved "Nar.SDL.Video.WindowEvent#WindowEventMoved"
#define Nar_SDL_Video_WindowEvent__WindowEventResized "Nar.SDL.Video.WindowEvent#WindowEventResized"
#define Nar_SDL_Video_WindowEvent__WindowEventSizeChanged "Nar.SDL.Video.WindowEvent#WindowEventSizeChanged"
#define Nar_SDL_Video_WindowEvent__WindowEventMinimized "Nar.SDL.Video.WindowEvent#WindowEventMinimized"
#define Nar_SDL_Video_WindowEvent__WindowEventMaximized "Nar.SDL.Video.WindowEvent#WindowEventMaximized"
#define Nar_SDL_Video_WindowEvent__WindowEventRestored "Nar.SDL.Video.WindowEvent#WindowEventRestored"
#define Nar_SDL_Video_WindowEvent__WindowEventEnter "Nar.SDL.Video.WindowEvent#WindowEventEnter"
#define Nar_SDL_Video_WindowEvent__WindowEventLeave "Nar.SDL.Video.WindowEvent#WindowEventLeave"
#define Nar_SDL_Video_WindowEvent__WindowEventFocusGained "Nar.SDL.Video.WindowEvent#WindowEventFocusGained"
#define Nar_SDL_Video_WindowEvent__WindowEventFocusLost "Nar.SDL.Video.WindowEvent#WindowEventFocusLost"
#define Nar_SDL_Video_WindowEvent__WindowEventClose "Nar.SDL.Video.WindowEvent#WindowEventClose"
#define Nar_SDL_Video_WindowEvent__WindowEventTakeFocus "Nar.SDL.Video.WindowEvent#WindowEventTakeFocus"
#define Nar_SDL_Video_WindowEvent__WindowEventHitTest "Nar.SDL.Video.WindowEvent#WindowEventHitTest"
#define Nar_SDL_Video_WindowEvent__WindowEventIccProfChanged "Nar.SDL.Video.WindowEvent#WindowEventIccProfChanged"
#define Nar_SDL_Video_WindowEvent__WindowEventDisplayChanged "Nar.SDL.Video.WindowEvent#WindowEventDisplayChanged"

#define Nar_SDL_Video_DisplayEvent "Nar.SDL.Video.DisplayEvent"
#define Nar_SDL_Video_DisplayEvent__DisplayEventNone "Nar.SDL.Video.DisplayEvent#DisplayEventNone"
#define Nar_SDL_Video_DisplayEvent__DisplayEventOrientation "Nar.SDL.Video.DisplayEvent#DisplayEventOrientation"
#define Nar_SDL_Video_DisplayEvent__DisplayEventConnected "Nar.SDL.Video.DisplayEvent#DisplayEventConnected"
#define Nar_SDL_Video_DisplayEvent__DisplayEventDisconnected "Nar.SDL.Video.DisplayEvent#DisplayEventDisconnected"
#define Nar_SDL_Video_DisplayEvent__DisplayEventMoved "Nar.SDL.Video.DisplayEvent#DisplayEventMoved"

#define Nar_SDL_Video_Orientation "Nar.SDL.Video.Orientation"
#define Nar_SDL_Video_Orientation__OrientationUnknown "Nar.SDL.Video.Orientation#OrientationUnknown"
#define Nar_SDL_Video_Orientation__OrientationLandscape "Nar.SDL.Video.Orientation#OrientationLandscape"
#define Nar_SDL_Video_Orientation__OrientationLandscapeFlipped "Nar.SDL.Video.Orientation#OrientationLandscapeFlipped"
#define Nar_SDL_Video_Orientation__OrientationPortrait "Nar.SDL.Video.Orientation#OrientationPortrait"
#define Nar_SDL_Video_Orientation__OrientationPortraitFlipped "Nar.SDL.Video.Orientation#OrientationPortraitFlipped"

#define Nar_SDL_Video_FlashOperation "Nar.SDL.Video.FlashOperation"
#define Nar_SDL_Video_FlashOperation__FlashOperationCancel "Nar.SDL.Video.FlashOperation#FlashOperationCancel"
#define Nar_SDL_Video_FlashOperation__FlashOperationBriefly "Nar.SDL.Video.FlashOperation#FlashOperationBriefly"
#define Nar_SDL_Video_FlashOperation__FlashOperationUntilFocused "Nar.SDL.Video.FlashOperation#FlashOperationUntilFocused"

#define Nar_SDL_Video_GLAttr "Nar.SDL.Video.GLAttr"
#define Nar_SDL_Video_GLAttr__GLAttrRedSize "Nar.SDL.Video.GLAttr#GLAttrRedSize"
#define Nar_SDL_Video_GLAttr__GLAttrGreenSize "Nar.SDL.Video.GLAttr#GLAttrGreenSize"
#define Nar_SDL_Video_GLAttr__GLAttrBlueSize "Nar.SDL.Video.GLAttr#GLAttrBlueSize"
#define Nar_SDL_Video_GLAttr__GLAttrAlphaSize "Nar.SDL.Video.GLAttr#GLAttrAlphaSize"
#define Nar_SDL_Video_GLAttr__GLAttrBufferSize "Nar.SDL.Video.GLAttr#GLAttrBufferSize"
#define Nar_SDL_Video_GLAttr__GLAttrDoublebuffer "Nar.SDL.Video.GLAttr#GLAttrDoublebuffer"
#define Nar_SDL_Video_GLAttr__GLAttrDepthSize "Nar.SDL.Video.GLAttr#GLAttrDepthSize"
#define Nar_SDL_Video_GLAttr__GLAttrStencilSize "Nar.SDL.Video.GLAttr#GLAttrStencilSize"
#define Nar_SDL_Video_GLAttr__GLAttrAccumRedSize "Nar.SDL.Video.GLAttr#GLAttrAccumRedSize"
#define Nar_SDL_Video_GLAttr__GLAttrAccumGreenSize "Nar.SDL.Video.GLAttr#GLAttrAccumGreenSize"
#define Nar_SDL_Video_GLAttr__GLAttrAccumBlueSize "Nar.SDL.Video.GLAttr#GLAttrAccumBlueSize"
#define Nar_SDL_Video_GLAttr__GLAttrAccumAlphaSize "Nar.SDL.Video.GLAttr#GLAttrAccumAlphaSize"
#define Nar_SDL_Video_GLAttr__GLAttrStereo "Nar.SDL.Video.GLAttr#GLAttrStereo"
#define Nar_SDL_Video_GLAttr__GLAttrMultisamplebuffers "Nar.SDL.Video.GLAttr#GLAttrMultisamplebuffers"
#define Nar_SDL_Video_GLAttr__GLAttrMultisamplesamples "Nar.SDL.Video.GLAttr#GLAttrMultisamplesamples"
#define Nar_SDL_Video_GLAttr__GLAttrAcceleratedVisual "Nar.SDL.Video.GLAttr#GLAttrAcceleratedVisual"
#define Nar_SDL_Video_GLAttr__GLAttrRetainedBacking "Nar.SDL.Video.GLAttr#GLAttrRetainedBacking"
#define Nar_SDL_Video_GLAttr__GLAttrContextMajorVersion "Nar.SDL.Video.GLAttr#GLAttrContextMajorVersion"
#define Nar_SDL_Video_GLAttr__GLAttrContextMinorVersion "Nar.SDL.Video.GLAttr#GLAttrContextMinorVersion"
#define Nar_SDL_Video_GLAttr__GLAttrContextEgl "Nar.SDL.Video.GLAttr#GLAttrContextEgl"
#define Nar_SDL_Video_GLAttr__GLAttrContextFlags "Nar.SDL.Video.GLAttr#GLAttrContextFlags"
#define Nar_SDL_Video_GLAttr__GLAttrContextProfileMask "Nar.SDL.Video.GLAttr#GLAttrContextProfileMask"
#define Nar_SDL_Video_GLAttr__GLAttrShareWithCurrentContext "Nar.SDL.Video.GLAttr#GLAttrShareWithCurrentContext"
#define Nar_SDL_Video_GLAttr__GLAttrFramebufferSrgbCapable "Nar.SDL.Video.GLAttr#GLAttrFramebufferSrgbCapable"
#define Nar_SDL_Video_GLAttr__GLAttrContextReleaseBehavior "Nar.SDL.Video.GLAttr#GLAttrContextReleaseBehavior"
#define Nar_SDL_Video_GLAttr__GLAttrContextResetNotification "Nar.SDL.Video.GLAttr#GLAttrContextResetNotification"
#define Nar_SDL_Video_GLAttr__GLAttrContextNoError "Nar.SDL.Video.GLAttr#GLAttrContextNoError"
#define Nar_SDL_Video_GLAttr__GLAttrFloatbuffers "Nar.SDL.Video.GLAttr#GLAttrFloatbuffers"

#define Nar_SDL_Video_GLProfile "Nar.SDL.Video.GLProfile"
#define Nar_SDL_Video_GLProfile__GLProfileCore "Nar.SDL.Video.GLProfile#GLProfileCore"
#define Nar_SDL_Video_GLProfile__GLProfileCompatibility "Nar.SDL.Video.GLProfile#GLProfileCompatibility"
#define Nar_SDL_Video_GLProfile__GLProfileEs "Nar.SDL.Video.GLProfile#GLProfileEs"

#define Nar_SDL_Video_GLContext "Nar.SDL.Video.GLContext"
#define Nar_SDL_Video_GLContext__GLContextDebug "Nar.SDL.Video.GLContext#GLContextDebug"
#define Nar_SDL_Video_GLContext__GLContextForwardCompatible "Nar.SDL.Video.GLContext#GLContextForwardCompatible"
#define Nar_SDL_Video_GLContext__GLContextRobustAccess "Nar.SDL.Video.GLContext#GLContextRobustAccess"
#define Nar_SDL_Video_GLContext__GLContextResetIsolation "Nar.SDL.Video.GLContext#GLContextResetIsolation"

#define Nar_SDL_Video_GLContextReleaseBehavior "Nar.SDL.Video.GLContextReleaseBehavior"
#define Nar_SDL_Video_GLContextReleaseBehavior__GLContextReleaseBehaviorNone "Nar.SDL.Video.GLContextReleaseBehavior#GLContextReleaseBehaviorNone"
#define Nar_SDL_Video_GLContextReleaseBehavior__GLContextReleaseBehaviorFlush "Nar.SDL.Video.GLContextReleaseBehavior#GLContextReleaseBehaviorFlush"

#define Nar_SDL_Video_GLContextResetNotification "Nar.SDL.Video.GLContextResetNotification"
#define Nar_SDL_Video_GLContextResetNotification__GLContextResetNotificationNoNotification "Nar.SDL.Video.GLContextResetNotification#GLContextResetNotificationNoNotification"
#define Nar_SDL_Video_GLContextResetNotification__GLContextResetNotificationLoseContext "Nar.SDL.Video.GLContextResetNotification#GLContextResetNotificationLoseContext"

#define Nar_SDL_Video_HitTestResult "Nar.SDL.Video.HitTestResult"
#define Nar_SDL_Video_HitTestResult__HitTestNormal "Nar.SDL.Video.HitTestResult#HitTestNormal"
#define Nar_SDL_Video_HitTestResult__HitTestDraggable "Nar.SDL.Video.HitTestResult#HitTestDraggable"
#define Nar_SDL_Video_HitTestResult__HitTestResizeTopLeft "Nar.SDL.Video.HitTestResult#HitTestResizeTopLeft"
#define Nar_SDL_Video_HitTestResult__HitTestResizeTop "Nar.SDL.Video.HitTestResult#HitTestResizeTop"
#define Nar_SDL_Video_HitTestResult__HitTestResizeTopRight "Nar.SDL.Video.HitTestResult#HitTestResizeTopRight"
#define Nar_SDL_Video_HitTestResult__HitTestResizeRight "Nar.SDL.Video.HitTestResult#HitTestResizeRight"
#define Nar_SDL_Video_HitTestResult__HitTestResizeBottomRight "Nar.SDL.Video.HitTestResult#HitTestResizeBottomRight"
#define Nar_SDL_Video_HitTestResult__HitTestResizeBottom "Nar.SDL.Video.HitTestResult#HitTestResizeBottom"
#define Nar_SDL_Video_HitTestResult__HitTestResizeBottomLeft "Nar.SDL.Video.HitTestResult#HitTestResizeBottomLeft"
#define Nar_SDL_Video_HitTestResult__HitTestResizeLeft "Nar.SDL.Video.HitTestResult#HitTestResizeLeft"

#define Nar_SDL_Video_FullscreenMode "Nar.SDL.Video.FullscreenMode"
#define Nar_SDL_Video_FullscreenMode__FullscreenModeWindowed "Nar.SDL.Video.FullscreenMode#FullscreenModeWindowed"
#define Nar_SDL_Video_FullscreenMode__FullscreenModeBorderless "Nar.SDL.Video.FullscreenMode#FullscreenModeBorderless"
#define Nar_SDL_Video_FullscreenMode__FullscreenModeExclusive "Nar.SDL.Video.FullscreenMode#FullscreenModeExclusive"

#endif //NAR_SDL_H
